; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.filesystem = spiffs
board_build.partitions = default_16MB.csv
; monitor_filters = esp32_exception_decoder
build_unflags =
	-std=gnu++11
build_flags = 
	-O2
	-std=gnu++17
	-DCORE_DEBUG_LEVEL=0
	-DUART_SCLK_DEFAULT=UART_SCLK_APB
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
lib_deps = 
	m5stack/M5Unified@^0.2.11
	meganetaaan/m5stack-avatar@0.10.0
	bblanchon/ArduinoJson
	m5stack/M5GFX@^0.2.19
	m5stack/StackChan-BSP@^1.1.0
lib_ldf_mode = deep
check_tool = cppcheck
check_skip_packages = yes
check_flags =
	cppcheck: --enable=warning,style,performance,portability
	cppcheck: --suppress=*:*/.pio/libdeps/*
	cppcheck: --suppress=*:src/drivers/*
